version: "2.1"
services:
  ddclient:
    image: linuxserver/ddclient:3.9.1
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - .:/config
    restart: always
